### ISSUE TITLE
Sample Example Project Missing `GoogleSearch` Depdency

### ISSUE THREAD

**Issue by joshmgrant** [titusfortner/watir_install#4]
Using Ruby 2.4.1 (via rbenv), I did the following:

- Created the sample project from the main README
- Followed the instructions in the generated README
- Executed all steps until `rake spec`

Expected output: sample spec is executed including driving a browser.

Actual output: Error with the following output: 

```ruby
Failure/Error:
    class Home < Base
  
      element(:search_term) { browser.text_field(name: 'q')}
      element(:submit) { browser.button(name: 'btnG') }
  
      page_url { 'https://www.google.com/' }
  
      def search(data)
        fill_form(data)
        submit.click

NameError:
  uninitialized constant GoogleSearch::Base
  Did you mean?  Base64
# ./spec/support/pages/home.rb:2:in `<module:GoogleSearch>'
# ./spec/support/pages/home.rb:1:in `<top (required)>'
# ./spec/spec_helper.rb:7:in `<top (required)>'
# ./spec/search_spec.rb:1:in `require'
# ./spec/search_spec.rb:1:in `<top (required)>'
No examples found.
```

I also tried globally installing the GoogleSearch gem using `gem install google_search` but this did not change the above output.

**Comment by titusfortner** [comment]
Ah, yes, I screwed up the namespacing here. I also want to update our example to use a Watir controlled site rather than Google. :-/
